# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
          USER_SESSION_LENGTH: "1h"
          JWT_SECRET: "FOOBAR"
          APP_PORT: 3000
          DATABASE_URL: "postgres://tadoku:@localhost/tadoku_dev?sslmode=disable"
          DATABASE_MAX_IDLE_CONNS: 10
          DATABASE_MAX_OPEN_CONNS: 10
          TESTING_DATABASE_URL: "postgres://tadoku:@localhost/tadoku_dev?sslmode=disable"
          TESTING_DATABASE_MAX_IDLE_CONNS: 10
          TESTING_DATABASE_MAX_OPEN_CONNS: 10

      - image: circleci/postgres:11.1-alpine
        environment:
          POSTGRES_USER: tadoku
          POSTGRES_DB: tadoku_dev

    working_directory: /go/src/github.com/tadoku/api
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}-{{ checksum "tools.go" }}

      - run:
          name: Install gex
          command: go get github.com/izumin5210/gex/cmd/gex && make setup

      - run:
          name: Lint project
          command: make lint
      - run:
          name: Run migrations
          command: make migrate
      - run:
          name: Run tests
          command: go test -cover ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}-{{ checksum "tools.go" }}
          paths:
            - "/go/pkg/mod"