version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Japan
  open-pull-requests-limit: 10
  reviewers:
  - antonve
  assignees:
  - antonve
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.2.0
    - 6.2.1
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.20
  - dependency-name: date-fns-tz
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: date-fns
    versions:
    - 2.17.0
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: react-content-loader
    versions:
    - 6.0.1
  - dependency-name: next
    versions:
    - 10.0.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
