version: "3"

services:
  # This docker file is only used for debugging the docker build locally, use `yarn dev` for development.
  # TODO: Move all development inside docker container
  tadoku-web:
    build: .
    container_name: tadoku-web
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      API_ROOT: http://localhost:4000
      GHOST_KEY: 22c9b1088957389622d210662f
      GHOST_URL: https://blog.tadoku.app
      SESSION_COOKIE_NAME: session_token
