version: '3'

services:
  tadoku-api:
    build: .
    image: tadoku/api
    container_name: tadoku-api
    network_mode: bridge
    environment:
      VIRTUAL_HOST: api.tadoku.app
      VIRTUAL_PORT: $APP_PORT
    expose:
      - $APP_PORT
