version: '3'

services:
  tadoku-api:
    build: .
    image: tadoku/api
    container_name: tadoku-api
    network_mode: bridge
    restart: always
    environment:
      VIRTUAL_HOST: api.tadoku.app
      VIRTUAL_PORT: $APP_PORT
      LETSENCRYPT_HOST: api.tadoku.app
      LETSENCRYPT_EMAIL: hello@tadoku.app
    expose:
      - $APP_PORT
