version: 2
jobs:
  build:
    working_directory: ~/tadoku-web
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint project
          command: yarn lint
      - run:
          name: Create environment
          command: cp .env{.sample,}
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build production
          command: yarn build
      - run:
          name: Cancel if not a tag
          command: |
            if [ ! -n "$CIRCLE_TAG" ]
            then
              circleci-agent step halt
            fi
      - setup_remote_docker
      - run:
          name: Deploy image to Docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            IMAGE_NAME=tadoku/web
            docker build -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:${CIRCLE_SHA1}
            docker push $IMAGE_NAME

  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy-tadoku-web.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
