version: 2
jobs:
  build:
    working_directory: ~/tadoku-web
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint project
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build production
          command: yarn build

  build-push-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy image to Docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            IMAGE_NAME=tadoku/web
            docker build -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:${CIRCLE_SHA1}
            docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - build-push-image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
