name: build
on: push # change building to merges to master only
jobs:
  build:
    name: Build Tadoku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Build
        run: bazel build //...

      - name: Setup Docker config
        run: echo "${{ secrets.DOCKER_CONFIG }}" >> /tmp/docker/config.json

      - name: Push images
        run: |
          bazel run //services/tadoku-contest-api/cmd/migrate:image_push
